name: Build APK with Buildozer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel python3-dev git curl build-essential libtool \
            automake cmake pkg-config zlib1g-dev libc6-dev libncurses5-dev libstdc++6 libffi-dev libssl-dev libsqlite3-dev

      - name: Install Buildozer
        run: |
          python3 -m pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: skanirator-apk
          path: bin/*.apk
